### ISSUE TITLE
Installation automatically places files in user's home directory

### ISSUE THREAD

**Issue by yirkajk** [nvcleemp/conjecturing#11]
When `make` is run on conjecturing-0.12-CoCalc, the files conjecturing.py and expressions are placed into the users's home directory no matter what directory conjecturing-0.12-CoCalc was in.

Either this behavior should be made explicit in the installation instructions, or the files should be placed in the same directory that the folder is already in.

**Comment by nvcleemp** [comment]
Agree. The Cocalc installation was originally just a quick hack to get things done, but I think at the moment it is the most common way to use `conjecturing`, so this should indeed be addressed. I'll look into it.
